### ISSUE TITLE
Enable Model Completeness Checking 

### ISSUE THREAD

**Issue by jrleeman** [jrleeman/rsfmodel#6]
Add content to the empty readyCheck method that will verify that all things are set before the model will try to run.

```
def readyCheck(self):
    return True
```

**Comment by jrleeman** [comment]
Any recommendations on the best way to implement this, or if it should even be? @dopplershift

**Comment by dopplershift** [comment]
One way is to initialize all required parameters to `None`, and check all are no longer `None` for `readyCheck()`. 

You could eliminate the need by providing good defaults for some and requiring others in the constructors.
